### ISSUE TITLE
Had to convert input from dos-style to unix-style

### ISSUE THREAD

**Issue by addison-grant** [donatj/CsvToMarkdownTable#11]
I was running into a problem with a CSV that I suspect came from a mac or a windows computer, and the markdown wasn't rendering.

I didn't have a clue at first what the problem was, until I was scrolling across lines in the CSV in the Sublime text editor and I noticed what seemed like an extra pause going across an invisible character. I then opened the file in the Vim editor, and noticed a `^M` symbol. 

I did a little research and found that it was probably to do with how end-of-lines are formatted.

I used a program on my system, named dos2unix, to convert the file to unix-style. I think this was necessary for the end-of-line characters to be read properly.

Anyway, I hope this wasn't too vague. I can't share the file as it is due to it containing sensitive data. I could scrub the sensitive data out, if you think it would be helpful to have it as an example.

**Comment by addison-grant** [comment]
Oh, and this is a great tool! I was thinking of trying to write something similar, but then suspected it had been done :)

**Comment by donatj** [comment]
Thank you for your note.  I've fixed the issue and [tagged a release](https://github.com/donatj/CsvToMarkdownTable/releases/tag/v1.1.0). 

It has also been published to npm.
