### ISSUE TITLE
CSV doesn't observe quoted strings.

### ISSUE THREAD

**Issue by justinrknowles** [donatj/CsvToMarkdownTable#2]
When using a CSV format that has quoted values that contain a comma the tool splits the value into columns.

Given

```
1,2,3
a,b,c
a,"b,b",c
```

Expected:

| 1 | 2 | 3 |
| --- | --- | --- |
| a | b | c |
| a | b,b | c |

Actual

| 1 | 2 | 3 |  |
| --- | --- | --- | --- |
| a | b | c |  |
| a | "b | b" | c |

**Comment by donatj** [comment]
It's a known issue and on my todo list. I should find a prebuilt CSV parser instead of doing it myself. This was hacked together kind of quickly so I could post MySQL EXPLAIN output on github.

**Comment by anazard** [comment]
I've been using your code to build some tables and might have come up with a fix for this. Could I send you a PR?

**Comment by donatj** [comment]
@anazard I'd love a PR!
