### ISSUE TITLE
It does not work in China

### ISSUE THREAD

**Issue by tanhangbo** [donatj/CsvToMarkdownTable#3]
I have found it does not work in china unless I can access google:

```
<script src="//ajax.googleapis.com/ajax/libs/mootools/1.2.2/mootools-yui-compressed.js"></script>
```

So attached script can help those cannot access google.

**Comment by tanhangbo** [comment]
[mootools-yui-compressed.js.txt](https://github.com/donatj/CsvToMarkdownTable/files/235858/mootools-yui-compressed.js.txt)

**Comment by donatj** [comment]
The better answer would probably be just to rewrite the simple example UI JS not to require MooTools.

The MooTools/example UI is just there as a crutch to help illustrate the library.

**Comment by donatj** [comment]
I have removed the dependence on MooTools in the example entirely.
