### ISSUE TITLE
[ and ] in entries causes parsing issue

### ISSUE THREAD

**Issue by sc68cal** [donatj/CsvToMarkdownTable#83]
I have CSV data, as shown.

```
"foo";"bar";"baz"
"1";"2";"[foo -- bar baz]"
```

There appears to be an issue where the `[` and `]` causes the parser to break, and place the 2nd and third column together.

<img width="830" alt="Screen Shot 2022-10-10 at 1 23 41 PM" src="https://user-images.githubusercontent.com/506899/194921496-079a5794-0f3e-4185-9674-353b8a76efe9.png">

It should instead be able to take the `[` `]` and display it correctly, like shown below (but without the `[` and `]`)

<img width="837" alt="Screen Shot 2022-10-10 at 1 24 02 PM" src="https://user-images.githubusercontent.com/506899/194921539-533e8f84-abce-4642-859f-d642999dd38c.png">

**Comment by donatj** [comment]
Thank you for the heads up!

There was a bug when the proceeding quote was followed by a word separator. 

I have fixed the issue, [created release 1.2.0](https://github.com/donatj/CsvToMarkdownTable/releases/tag/v1.2.0) and updated the website (you may need to hard refresh).
