### ISSUE TITLE
csvToMarkdown is not a function

### ISSUE THREAD

**Issue by shy-Xu** [donatj/CsvToMarkdownTable#87]
I am trying to do this simple example
```
import { csvToMarkdown } from "csv-to-markdown-table";

console.log(csvToMarkdown("header1,header2,header3\nValue1,Value2,Value3", ",", true))
```

And I get `csvToMarkdown is not a function`, what should I do?

**Comment by shy-Xu** [comment]
Typescript+node

**Comment by donatj** [comment]
It would appear there is something wrong with the TypeScript definition. I think I need to change the `export` to `export default` - will investigate

In the meantime *this* does work though it is a hack

```ts
import csvToMarkdown from "csv-to-markdown-table";

console.log(
	(csvToMarkdown as any)("header1,header2,header3\nValue1,Value2,Value3", ",", true)
);
```

**Comment by donatj** [comment]
If you update to 1.3.0 it should now work as expected with 

```ts
import csvToMarkdown from "csv-to-markdown-table";

console.log(csvToMarkdown("header1,header2,header3\nValue1,Value2,Value3", ",", true))
```
